
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Entry inpQuery;
	
	private global::Gtk.Button btnExecQuery;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.Label lbQueryStatus;
	
	private global::Gtk.VSeparator vseparator1;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Label lbQueryResult;
	
	private global::Gtk.HSeparator hseparator1;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Entry inpSheetName;
	
	private global::Gtk.Button btnWriteToSheet;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Label lbWritingStatus;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.Label lbSheetInfo;
	
	private global::Gtk.Label label11;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Label lbEmail;
	
	private global::Gtk.Button btnAuthorize;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = "GSheetApp";
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.WidthRequest = 600;
		this.fixed1.HeightRequest = 280;
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = "Your Query :";
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w1.X = 30;
		w1.Y = 10;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.inpQuery = new global::Gtk.Entry ();
		this.inpQuery.WidthRequest = 425;
		this.inpQuery.CanFocus = true;
		this.inpQuery.Name = "inpQuery";
		this.inpQuery.IsEditable = true;
		this.inpQuery.InvisibleChar = '•';
		this.fixed1.Add (this.inpQuery);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.inpQuery]));
		w2.X = 25;
		w2.Y = 35;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnExecQuery = new global::Gtk.Button ();
		this.btnExecQuery.WidthRequest = 100;
		this.btnExecQuery.CanFocus = true;
		this.btnExecQuery.Name = "btnExecQuery";
		this.btnExecQuery.UseUnderline = true;
		this.btnExecQuery.Label = "_ExecuteQuery";
		this.fixed1.Add (this.btnExecQuery);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnExecQuery]));
		w3.X = 470;
		w3.Y = 35;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = "Query Status :";
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w4.X = 30;
		w4.Y = 80;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbQueryStatus = new global::Gtk.Label ();
		this.lbQueryStatus.Name = "lbQueryStatus";
		this.lbQueryStatus.LabelProp = "Unknown";
		this.fixed1.Add (this.lbQueryStatus);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lbQueryStatus]));
		w5.X = 125;
		w5.Y = 80;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.vseparator1 = new global::Gtk.VSeparator ();
		this.vseparator1.HeightRequest = 25;
		this.vseparator1.Name = "vseparator1";
		this.fixed1.Add (this.vseparator1);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.vseparator1]));
		w6.X = 300;
		w6.Y = 80;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = "Query Result :";
		this.fixed1.Add (this.label4);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
		w7.X = 320;
		w7.Y = 80;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbQueryResult = new global::Gtk.Label ();
		this.lbQueryResult.Name = "lbQueryResult";
		this.lbQueryResult.LabelProp = "Unknown";
		this.fixed1.Add (this.lbQueryResult);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lbQueryResult]));
		w8.X = 415;
		w8.Y = 80;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.WidthRequest = 530;
		this.hseparator1.HeightRequest = 3;
		this.hseparator1.Name = "hseparator1";
		this.fixed1.Add (this.hseparator1);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.hseparator1]));
		w9.X = 30;
		w9.Y = 120;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = "Sheet Filename :";
		this.fixed1.Add (this.label6);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
		w10.X = 30;
		w10.Y = 140;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.inpSheetName = new global::Gtk.Entry ();
		this.inpSheetName.WidthRequest = 425;
		this.inpSheetName.CanFocus = true;
		this.inpSheetName.Name = "inpSheetName";
		this.inpSheetName.IsEditable = true;
		this.inpSheetName.InvisibleChar = '•';
		this.fixed1.Add (this.inpSheetName);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.inpSheetName]));
		w11.X = 25;
		w11.Y = 165;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnWriteToSheet = new global::Gtk.Button ();
		this.btnWriteToSheet.WidthRequest = 100;
		this.btnWriteToSheet.CanFocus = true;
		this.btnWriteToSheet.Name = "btnWriteToSheet";
		this.btnWriteToSheet.UseUnderline = true;
		this.btnWriteToSheet.Label = "_Write to Sheet";
		this.fixed1.Add (this.btnWriteToSheet);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnWriteToSheet]));
		w12.X = 470;
		w12.Y = 165;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = "Writing Status :";
		this.fixed1.Add (this.label7);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label7]));
		w13.X = 30;
		w13.Y = 210;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbWritingStatus = new global::Gtk.Label ();
		this.lbWritingStatus.Name = "lbWritingStatus";
		this.lbWritingStatus.LabelProp = "Unknown";
		this.fixed1.Add (this.lbWritingStatus);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lbWritingStatus]));
		w14.X = 130;
		w14.Y = 210;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = "Spreadsheet Fileinfo :";
		this.fixed1.Add (this.label9);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label9]));
		w15.X = 30;
		w15.Y = 240;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbSheetInfo = new global::Gtk.Label ();
		this.lbSheetInfo.Name = "lbSheetInfo";
		this.lbSheetInfo.LabelProp = "Unknown";
		this.fixed1.Add (this.lbSheetInfo);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lbSheetInfo]));
		w16.X = 165;
		w16.Y = 240;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = "© 2015 BI Dept.";
		this.label11.Justify = ((global::Gtk.Justification)(1));
		this.fixed1.Add (this.label11);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label11]));
		w17.X = 470;
		w17.Y = 275;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = "Authorized as :";
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w18.X = 30;
		w18.Y = 270;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbEmail = new global::Gtk.Label ();
		this.lbEmail.Name = "lbEmail";
		this.lbEmail.LabelProp = "Unknown";
		this.fixed1.Add (this.lbEmail);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lbEmail]));
		w19.X = 125;
		w19.Y = 270;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnAuthorize = new global::Gtk.Button ();
		this.btnAuthorize.WidthRequest = 100;
		this.btnAuthorize.CanFocus = true;
		this.btnAuthorize.Name = "btnAuthorize";
		this.btnAuthorize.UseUnderline = true;
		this.btnAuthorize.Label = "_Reauthorize";
		this.fixed1.Add (this.btnAuthorize);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnAuthorize]));
		w20.X = 471;
		w20.Y = 200;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 600;
		this.DefaultHeight = 316;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnExecQuery.Clicked += new global::System.EventHandler (this.ExecQuery);
		this.btnExecQuery.Pressed += new global::System.EventHandler (this.UpdateQueryStatus);
		this.btnWriteToSheet.Clicked += new global::System.EventHandler (this.WriteToSheet);
		this.btnWriteToSheet.Pressed += new global::System.EventHandler (this.UpdateWritingStatus);
		this.btnAuthorize.Clicked += new global::System.EventHandler (this.ReauthorizeClicked);
	}
}
